apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: qbittorrent
    targetRevision: "13.5.2"
    helm:
      values: |-
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: latest
          pullPolicy: IfNotPresent

        env:
          TZ: America/Sao_Paulo
          PUID: "1000"
          PGID: "1000"
          WEBUI_PORT: "8080"

        service:
          main:
            ports:
              http:
                port: 8080

        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: letsencrypt-prod
              external-dns.alpha.kubernetes.io/hostname: qbittorrent.kevindev.com.br
              external-dns.alpha.kubernetes.io/ttl: "300"
            hosts:
              - host: qbittorrent.kevindev.com.br
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - qbittorrent.kevindev.com.br
                secretName: qbittorrent-tls-cert

        persistence:
          config:
            enabled: true
            type: pvc
            accessMode: ReadWriteOnce
            size: 1Gi
            retain: true

          downloads:
            enabled: true
            type: pvc
            existingClaim: radarr-downloads
            mountPath: /downloads

        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi

        probes:
          liveness:
            enabled: true
            initialDelaySeconds: 30
          readiness:
            enabled: true
            initialDelaySeconds: 30

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true