apiVersion: v1
kind: ConfigMap
metadata:
  name: lavalink-config
  namespace: lavalink
data:
  application.yml: |
    server:
      port: 2333
      address: 0.0.0.0
      http2:
        enabled: false
    plugins:
      youtube:
        enabled: true
        allowSearch: true
        allowDirectVideoIds: true
        allowDirectPlaylistIds: true
        clients:
          - MUSIC
          - WEB
          - ANDROID_MUSIC
          - ANDROID_CREATOR
          - TVHTML5EMBEDDED
        oauth:
          enabled: false
    lavalink:
      server:
        password: "youshallnotpass"
        sources:
          youtube: true
          bandcamp: true
          soundcloud: true
          twitch: true
          vimeo: true
          nico: true
          http: true
          local: false
        filters:
          volume: true
          equalizer: true
          karaoke: true
          timescale: true
          tremolo: true
          vibrato: true
          distortion: true
          rotation: true
          channelMix: true
          lowPass: true
        nonAllocatingFrameBuffer: false
        bufferDurationMs: 400
        frameBufferDurationMs: 5000
        opusEncodingQuality: 10
        resamplingQuality: "LOW"
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 6
        playerUpdateInterval: 5
        youtubeSearchEnabled: true
        soundcloudSearchEnabled: true
        gc-warnings: true
      plugins:
        - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.2"
          snapshot: false
    metrics:
      prometheus:
        enabled: false
        endpoint: "/metrics"
    sentry:
      dsn: ""
      environment: ""
    logging:
      file:
        path: ./logs/
      level:
        root: INFO
        lavalink: INFO
        dev.lavalink.youtube.clients.Client: INFO
        dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
      request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includeQueryString: true
        includePayload: true
        maxPayloadLength: 10000
      logback:
        rollingpolicy:
          max-file-size: 1GB
          max-history: 30