apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: radarr
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: radarr
    targetRevision: "16.3.2"
    helm:
      values: |-
        image:
          repository: lscr.io/linuxserver/radarr
          tag: latest
          pullPolicy: IfNotPresent

        env:
          TZ: America/Sao_Paulo
          PUID: "1000"
          PGID: "1000"

        service:
          main:
            ports:
              http:
                port: 7878

        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: letsencrypt-prod
              external-dns.alpha.kubernetes.io/hostname: radarr.kevindev.com.br
              external-dns.alpha.kubernetes.io/ttl: "300"
            hosts:
              - host: radarr.kevindev.com.br
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - radarr.kevindev.com.br
                secretName: radarr-tls-cert

        persistence:
          config:
            enabled: true
            type: pvc
            accessMode: ReadWriteOnce
            size: 5Gi
            retain: true

          downloads:
            enabled: true
            type: pvc
            accessMode: ReadWriteOnce
            size: 50Gi
            retain: true
            mountPath: /downloads

          movies:
            enabled: true
            type: pvc
            existingClaim: jellyfin-media
            mountPath: /movies

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi

        probes:
          liveness:
            enabled: true
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readiness:
            enabled: true
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

        nodeSelector: {}
        tolerations: []
        affinity: {}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true