{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.parameters }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-parameters
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
  data:
    {{- range .Values.externalSecrets.parameters }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .path }}
    {{- end }}
{{- end }}