apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: jackett
    targetRevision: "11.7.2"
    helm:
      values: |-
        image:
          repository: lscr.io/linuxserver/jackett
          tag: latest
          pullPolicy: IfNotPresent

        env:
          TZ: America/Sao_Paulo
          PUID: "1000"
          PGID: "1000"
          AUTO_UPDATE: "true"

        service:
          main:
            ports:
              http:
                port: 9117

        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: letsencrypt-prod
              external-dns.alpha.kubernetes.io/hostname: jackett.kevindev.com.br
              external-dns.alpha.kubernetes.io/ttl: "300"
            hosts:
              - host: jackett.kevindev.com.br
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - jackett.kevindev.com.br
                secretName: jackett-tls-cert

        persistence:
          config:
            enabled: true
            type: pvc
            accessMode: ReadWriteOnce
            size: 1Gi
            retain: true

          downloads:
            enabled: false

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi

        probes:
          liveness:
            enabled: true
            initialDelaySeconds: 30
            periodSeconds: 30
          readiness:
            enabled: true
            initialDelaySeconds: 30
            periodSeconds: 30

        nodeSelector: {}
        tolerations: []
        affinity: {}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true